---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudstorages.yaml
  # TODO: Migrate any resources not using KRO into new KRO resource
  - cephobjectstoreuser.yaml
  - objectbucketclaims.yaml
  - serviceaccount.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml
