---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-external
  namespace: kubernetes-api-external
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 6443
      targetPort: https
