---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres
spec:
  destination:
    create: true
    name: grafana-db-app
    overwrite: true
  hmacSecretData: true
  mount: ""
  path: grafana/postgres/db
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: postgres
