---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../clusters/homelab.wojoinc.xyz/coder
resources:
  - certificate.yaml
  - cluster.yaml
  - ingress.yaml
  - namespace.yaml
  - podmonitor.yaml
  - pvc.yaml
  - serverstransport.yaml
  - serviceaccount.yaml
  - vaultauths.yaml
  - vaultstaticsecrets.yaml
