---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../clusters/homelab.wojoinc.xyz/authentik
resources:
  - cluster.yaml
  - podmonitor.yaml
  - serviceaccount.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml
