---
serviceAccount:
  create: true
service:
  port: 6767
image:
  repository: ghcr.io/home-operations/bazarr
  tag: 1.5.4
ingress:
  main:
    forwardAuth:
      allowedGroups:
        - Bazarr-Admins
