---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/home-operations/plex
    newTag: 1.43.0.10492
resources:
  - deployment.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - services.yaml
