---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: tubearchivist
    includeTemplates: true
    includeSelectors: true
components:
  - ../components/forward-auth
  - ../../../common/ingress-publish-internal
  - ../../../env/prod/ingress-tls
  - ../../../clusters/homelab.wojoinc.xyz/tubearchivist
resources:
  - deployment.yaml
  - elasticsearch.yaml
  - ingress.yaml
  - redis.yaml
  - service.yaml
  - serviceaccounts.yaml
  - vaultauths.yaml
  - vaultstaticsecrets.yaml
