---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/flaresolverr/flaresolverr
    newTag: v3.4.6
labels:
  - pairs:
      app.kubernetes.io/name: "flaresolverr"
      app.kubernetes.io/instance: "flaresolverr"
    includeTemplates: true
    includeSelectors: true
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
