serviceAccount:
  create: true
service:
  port: 9696
image:
  repository: ghcr.io/home-operations/prowlarr
  tag: 2.3.1
ingress:
  main:
    forwardAuth:
      allowedGroups:
        - Prowlarr-Admins
