controller:
  timezone: America/Chicago

services:
  webUI:
    additionalAnnotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https
      traefik.ingress.kubernetes.io/service.serverstransport: omada-upstream-tls@kubernetescrd
  portal:
    additionalAnnotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https
      traefik.ingress.kubernetes.io/service.serverstransport: omada-upstream-tls@kubernetescrd

image:
  tag: 6.1.0.19
