---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.2.3
labels:
  - pairs:
      app.kubernetes.io/part-of: immich
resources:
  - certificates.yaml
  - cluster.yaml
  - configmaps.yaml
  - database.yaml
  - deployments.yaml
  - ingress.yaml
  - podmonitor.yaml
  - redisreplication.yaml
  - redissentinel.yaml
  - serviceaccounts.yaml
  - services.yaml
  - vaultauths.yaml
  - vaultstaticsecrets.yaml
