---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cdis.cdi.kubevirt.io.yaml
  - cdi.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
