---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: replacement-config
    options:
      annotations:
        # Skip rendering CM in build output
        config.kubernetes.io/local-config: "true"
    literals:
      - port=8989
      - flavor=sonarr
components:
  - ../../app/arr/components/persistence
  - ../../env/prod/arr/media-volume
images:
  - name: placeholder
    newName: ghcr.io/home-operations/sonarr
    newTag: 4.0.16
labels:
  - pairs:
      app.kubernetes.io/name: "sonarr"
      app.kubernetes.io/instance: "sonarr"
    includeTemplates: true
    includeSelectors: true
