ingresses:
  web-ui:
    enabled: true
    host: "omada.wojoinc.xyz"
    className: "traefik-external"
    additionalLabels: {}
    additionalAnnotations:
      cert-manager.io/cluster-issuer: acme
      dns.homelab.wojoinc.xyz/publish-internal: ""
  portal:
    enabled: true
    host: "captive.wojoinc.xyz"
    className: "traefik-external"
    additionalLabels: {}
    additionalAnnotations:
      cert-manager.io/cluster-issuer: acme
      dns.homelab.wojoinc.xyz/publish-internal: ""
persistence:
  data:
    enabled: true
    storageClassName: "rook-rbd-fast"
    size: 1Gi
  logs:
    enabled: true
    storageClassName: "rook-rbd-fast"
    size: 1Gi
services:
  controller:
    type: LoadBalancer
    additionalAnnotations:
      lbipam.cilium.io/ips: "10.3.8.10"
      lbipam.cilium.io/sharing-key: "omada"
