---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Allow kustomize to handle strategic merges on fields that grafana-operator
# for some reason re-implemented rather than referencing the built-in specs...
openapi:
  path: grafanas.openapi.json
resources:
  - grafana.yaml
