---
# Source: bookstack/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  labels:
    helm.sh/chart: "bookstack"
    app.kubernetes.io/version: "25.2.0"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "bookstack"
    app.kubernetes.io/instance: "bookstack"
  annotations: {}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: "bookstack"
      app.kubernetes.io/instance: "bookstack"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "bookstack"
        app.kubernetes.io/instance: "bookstack"
    spec:
      # TODO handle service account creation
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 33
        runAsGroup: 33
        runAsUser: 33
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: bookstack
          image: "docker.io/solidnerd/bookstack:25.12.3"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
          env:
            - name: APP_URL
              value: https://docs.wojoinc.xyz
            - name: APP_TIMEZONE
              value: America/Chicago
            - name: AUTH_METHOD
              value: oidc
            - name: APP_DEFAULT_DARK_MODE
              value: "true"
            - name: EXPORT_PAGE_SIZE
              value: letter
          envFrom:
            - secretRef:
                name: bookstack-env
            - secretRef:
                name: bookstack-db-auth
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: 1500m
              memory: 1532Mi
            requests:
              cpu: 200m
              memory: 100Mi
