---
# Source: bookstack/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstack
  labels:
    helm.sh/chart: "bookstack"
    app.kubernetes.io/version: "25.2.0"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "bookstack"
    app.kubernetes.io/instance: "bookstack"
  annotations:
    cert-manager.io/cluster-issuer: acme
    dns.homelab.wojoinc.xyz/publish-external: "true"
    external-dns.alpha.kubernetes.io/target: wojoinc.xyz.
spec:
  ingressClassName: "traefik-external"
  tls:
    - hosts:
        - docs.wojoinc.xyz
      secretName: bookstack-cert
  rules:
    - host: "docs.wojoinc.xyz"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: bookstack
                port:
                  number: 8080