---
# Source: bookstack/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookstack
  labels:
    helm.sh/chart: "bookstack"
    app.kubernetes.io/version: "25.2.0"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "bookstack"
    app.kubernetes.io/instance: "bookstack"
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "bookstack"
    app.kubernetes.io/instance: "bookstack"